renamed doas -> duoas

diff --git a/viduoas b/viduoas
--- a/viduoas
+++ b/viduoas
@@ -15,8 +15,8 @@
 # TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 # PERFORMANCE OF THIS SOFTWARE.
 
-# Edit a temporary copy of the doas.conf file and check it for syntax
-# errors before installing it as the actual doas.conf file.
+# Edit a temporary copy of the duoas.conf file and check it for syntax
+# errors before installing it as the actual duoas.conf file.
 
 set -eu
 
@@ -27,8 +27,8 @@ PROG="${0##*/}"
 
 umask 022
 
-DOAS_CONF=@DOAS_CONF@
-doas_conf_mode="0600"
+DUOAS_CONF=@DUOAS_CONF@
+duoas_conf_mode="0600"
 
 die()
 {
@@ -87,11 +87,11 @@ usage()
 Usage:	${PROG} [-n] [file]
 	${PROG} -h
 
-Edit a temporary copy of a doas configuration file and check it for
+Edit a temporary copy of a duoas configuration file and check it for
 syntax errors before installing it as the actual configuration file.
 
 When no file is named, ${PROG} will edit the default configuration file
-for doas(1): @DOAS_CONF@
+for duoas(1): @DUOAS_CONF@
 
 Options:
 -h	Show this usage.
@@ -115,7 +115,7 @@ shift $((${OPTIND} - 1))
 
 case ${#} in
 0) ;;
-1) DOAS_CONF="${1}";;
+1) DUOAS_CONF="${1}";;
 *) usage 1>&2; exit 1;;
 esac
 
@@ -125,73 +125,73 @@ case ${noop} in
 *) noop=true; exec >/dev/null 2>&1;;
 esac
 
-case "${DOAS_CONF}" in
+case "${DUOAS_CONF}" in
 -*)
-    warn "Invalid filename: ${DOAS_CONF}"
-    die  "Try using './${DOAS_CONF}' instead"
+    warn "Invalid filename: ${DUOAS_CONF}"
+    die  "Try using './${DUOAS_CONF}' instead"
     ;;
 esac
 
-doas_conf_dir="$(dirname "${DOAS_CONF}")"
-doas_conf_base="$(basename "${DOAS_CONF}")"
-DOAS_CONF="${doas_conf_dir}/${doas_conf_base}"
-doas_lock_file="${DOAS_CONF}.lck"
+duoas_conf_dir="$(dirname "${DUOAS_CONF}")"
+duoas_conf_base="$(basename "${DUOAS_CONF}")"
+DUOAS_CONF="${duoas_conf_dir}/${duoas_conf_base}"
+duoas_lock_file="${DUOAS_CONF}.lck"
 
 # These checks are only for producing nicer diagnostic messages to the
 # user.  They are not relied on by the rest of the code.
 
-if [ ! -e "${doas_conf_dir}" ]
+if [ ! -e "${duoas_conf_dir}" ]
 then
-    die "${doas_conf_dir} does not exist"
+    die "${duoas_conf_dir} does not exist"
 fi
 
-if [ ! -d "${doas_conf_dir}" ]
+if [ ! -d "${duoas_conf_dir}" ]
 then
-    die "${doas_conf_dir} is not a directory"
+    die "${duoas_conf_dir} is not a directory"
 fi
 
-if [ ! -w "${doas_conf_dir}" ]
+if [ ! -w "${duoas_conf_dir}" ]
 then
-    owner="$(owner_of "${doas_conf_dir}")"
-    warn "${doas_conf_dir} is not writable"
+    owner="$(owner_of "${duoas_conf_dir}")"
+    warn "${duoas_conf_dir} is not writable"
     die "You probably need to run ${PROG} as ${owner:-root}"
 fi
 
-tmp_doas="$(mktemp "${DOAS_CONF}.XXXXXXXXXX")" \
+tmp_duoas="$(mktemp "${DUOAS_CONF}.XXXXXXXXXX")" \
 || die "You probably need to run ${PROG} as root"
-set_trap_rm "${tmp_doas}"
+set_trap_rm "${tmp_duoas}"
 
 # It is important that the ln(1) command fails if the target already
 # exists.  Some versions are known to behave like "ln -f" by default
 # (removing any existing target).  Adjust PATH to avoid such ln(1)
 # implementations.
 
-tmp_test_ln="$(mktemp "${DOAS_CONF}.XXXXXXXXXX")"
-set_trap_rm "${tmp_doas}" "${tmp_test_ln}"
+tmp_test_ln="$(mktemp "${DUOAS_CONF}.XXXXXXXXXX")"
+set_trap_rm "${tmp_duoas}" "${tmp_test_ln}"
 
-if ln "${tmp_doas}" "${tmp_test_ln}" 2>/dev/null
+if ln "${tmp_duoas}" "${tmp_test_ln}" 2>/dev/null
 then
     die 'ln(1) is not safe for creating lock files, bailing'
 fi
 
-# If a doas.conf file exists, copy it into the temporary file for
+# If a duoas.conf file exists, copy it into the temporary file for
 # editing.  If none exist, the editor will open with an empty file.
 
-if [ -f "${DOAS_CONF}" ]
+if [ -f "${DUOAS_CONF}" ]
 then
-    if [ -r "${DOAS_CONF}" ]
+    if [ -r "${DUOAS_CONF}" ]
     then
-	cp "${DOAS_CONF}" "${tmp_doas}"
+	cp "${DUOAS_CONF}" "${tmp_duoas}"
     else
-	die "${DOAS_CONF} is not readable"
+	die "${DUOAS_CONF} is not readable"
     fi
 fi
 
 if ${noop}
 then
-    if ! doas -C "${DOAS_CONF}"
+    if ! duoas -C "${DUOAS_CONF}"
     then
-        die "${DOAS_CONF} contains syntax errors."
+        die "${DUOAS_CONF} contains syntax errors."
     fi
     warn 'OK: Prerequisite checks passed'
     exit 0
@@ -199,43 +199,43 @@ fi
 
 # Link the temporary file to the lock file.
 
-if ln "${tmp_doas}" "${doas_lock_file}"
+if ln "${tmp_duoas}" "${duoas_lock_file}"
 then
-    set_trap_rm "${tmp_doas}" "${tmp_test_ln}" "${doas_lock_file}"
+    set_trap_rm "${tmp_duoas}" "${tmp_test_ln}" "${duoas_lock_file}"
 else
-    die "${DOAS_CONF} is already locked"
+    die "${DUOAS_CONF} is already locked"
 fi
 
 # Some versions of vi(1) exit with a code that reflects the number of
 # editing errors made.  This is why we ignore the exit code from the
 # editor.
 
-"${EDITOR:-vi}" "${tmp_doas}" || true
+"${EDITOR:-vi}" "${tmp_duoas}" || true
 
-while ! doas -C "${tmp_doas}"
+while ! duoas -C "${tmp_duoas}"
 do
-    warn "Press enter to edit doas.conf again to fix it,"
+    warn "Press enter to edit duoas.conf again to fix it,"
     warn "or interrupt ($(get_intr)) to cancel."
     read status
-    "${EDITOR:-vi}" "${tmp_doas}" || true
+    "${EDITOR:-vi}" "${tmp_duoas}" || true
 done
 
-# Use mv(1) to rename the temporary file to doas.conf as it is atomic.
-# Update: No longer use mv as it messes up permissions on the doas.conf file.
+# Use mv(1) to rename the temporary file to duoas.conf as it is atomic.
+# Update: No longer use mv as it messes up permissions on the duoas.conf file.
 # Use install with ownership set to root.
 
-if [ -s "${tmp_doas}" ]
+if [ -s "${tmp_duoas}" ]
 then
-    if cmp -s "${tmp_doas}" "${DOAS_CONF}"
+    if cmp -s "${tmp_duoas}" "${DUOAS_CONF}"
     then
 	warn "No changes made"
-	warn "${DOAS_CONF} unchanged"
+	warn "${DUOAS_CONF} unchanged"
     else
-	install -o root -m "${doas_conf_mode}" \
-	    "${tmp_doas}" "${DOAS_CONF}" \
-	&& warn "${DOAS_CONF} updated"
+	install -o root -m "${duoas_conf_mode}" \
+	    "${tmp_duoas}" "${DUOAS_CONF}" \
+	&& warn "${DUOAS_CONF} updated"
     fi
 else
-    warn "Not installing an empty doas.conf file"
-    warn "${DOAS_CONF} unchanged"
+    warn "Not installing an empty duoas.conf file"
+    warn "${DUOAS_CONF} unchanged"
 fi
